name: Check Datahub Jars

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "**.md"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_jars:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        command:
          [
            "datahub-client",
            "datahub-protobuf",
            "spark-lineage"
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 800
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: check ${{ matrix.command }} jar
        run: |
          ./gradlew :metadata-integration:java:${{ matrix.command }}:build --info
          ./gradlew :metadata-integration:java:${{ matrix.command }}:javadoc
